on:
  workflow_dispatch:

jobs:
  build-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout script repo from upstream
        uses: actions/checkout@v4
        with:
          path: test
  
      - name: test commit
        run: echo ${ cd test && git rev-parse HEAD }
